### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'version_prefix'

### ISSUE THREAD

**Issue by jailge** [ashleysommer/sanic-restplus#27] opened 2021-08-24 07:37 UTC
Hi, I currently use python3.7, sanic 21.6.2 and sanic-restplus 0.6.0.
When I run my project, I got a type error as below:

`  File "/Users/jailge/PycharmProjects/eslogsystem/sanic-ls-service/venv/lib/python3.7/site-packages/sanic_plugin_toolkit/realm.py", line 350, in _plugin_register_app_route
    fr = SanicFutureRoute(r_handler, uri, name=name, **kwargs)
TypeError: __new__() missing 1 required positional argument: 'version_prefix'`

**Comment by ashleysommer** [comment] 2021-08-30 23:51
Hi @jailge 
Thanks for the report. This is a bug in Sanic-Plugin-Toolkit. I'll create a copy of this issue in that repo, and update you here.

**Comment by ashleysommer** [comment] 2021-08-30 23:55
Also, this is a duplicate of https://github.com/ashleysommer/sanic-restplus/pull/26

**Comment by ashleysommer** [comment] 2021-08-31 01:44
Fix released in Sanic-Restplus v0.6.1

**Comment by ashleysommer** [comment] 2021-08-31 01:44
Fixed by #26

**Closed as completed by ashleysommer** 2021-08-31 01:44 UTC
